export interface PersonaFisicaMassiva {
    'Progressivo' : string,
    'cod_discale' : string,
    'tipo_elab' : string,
    'nome_prodotto' : string,
    'cognome' : string,
    'nome' : string,
    'denominaz' : string,
    'codfisc' : string,
    'comRes' : string,
    'sede' : string,
    'indirizzo' : string,
    'telefono' : string,
    'cellulare' : string,
    'note' : string,
    'urgente' : string,
    'Cognome' : string,
    'Nome' : string,
    'Data Di Nascita' : string,
    'Provincia' : string,
    'Comune' : string,
    'Codice Fiscale' : string,
    'Utenze Telefoniche' : string,
    'Note Utenze' : string,
    'Codice Fiscale Aggiornato' : string,
    'Verifiche Anagrafiche' : string,
    'Dati Residenza ' : string,
    'Indirizzo' : string,
    'Cap' : string,
    'Comune ' : string,
    'Provincia ' : string,
    'Data Decesso' : string,
    'Flag occupazione' : string,
    'Categoria' : string,
    'Datore Di Lavoro' : string,
    'Partita Iva' : string,
    'Codice Fiscale ' : string,
    'Indirizzo ' : string,
    'Cap ' : string,
    'Comune  ' : string,
    'Pronvincia ' : string,
    'Emolumenti' : string,
    'Note' : string,
    'Verifiche Occupazione' : string,
    'Flag Banca' : string,
    'Stato Rapporto' : string,
    'Istituto Bancario' : string,
    'ABI' : string,
    'CAB' : string,
    'P.Iva/Cod.Fiscale' : string,
    'Indirizzo  ' : string,
    'Cap  ' : string,
    'Comune   ' : string,
    'Provincia  ' : string,
    'Flag Immobili' : string,
    'Protesti' : string,
    'Pregiudizievoli' : string,
    'Procedure Concorsuali' : string,
    'Flag Veicoli' : string,

}